version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "${CI_ZIPKIN_PORT:-9411}:9411"
    networks:
      - microservices_network

  service-discovery-container:
    image: selimhorri/service-discovery-ecommerce-boot:0.1.0
    ports:
      - "${CI_SERVICE_DISCOVERY_PORT:-8761}:8761"
    networks:
      - microservices_network
    environment:
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat </dev/null >/dev/tcp/127.0.0.1/8761'"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 10

  cloud-config-container:
    image: selimhorri/cloud-config-ecommerce-boot:0.1.0
    ports:
      - "${CI_CLOUD_CONFIG_PORT:-9296}:9296"
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat </dev/null >/dev/tcp/127.0.0.1/9296'"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 10

networks:
  microservices_network:
    driver: bridge



